Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.hostname = "JavaEEStack"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :private_network,
	ip: "192.168.50.4",
	netmask: "255.255.255.0"
  end