
Vagrant.configure(2) do |config|
  
  config.vm.box = "chef/centos-7.0"

	config.vm.provider :azure do |azure|
       #azure.mgmt_certificate = 'YOUR AZURE MANAGEMENT CERTIFICATE'
        azure.mgmt_endpoint = 'https://management.core.windows.net'
        azure.subscription_id = '0a7216cb-f2af-4233-8f98-d5e5871b7040'
        

        azure.vm_image = 'lampstack09'
        azure.vm_user = 'vagrant' # defaults to 'vagrant' if not provided
        azure.vm_password = 'Lampstack09' # min 8 characters. should contain a lower case letter, an uppercase letter, a number and a special character

        azure.vm_name = 'LampStack' 
        azure.cloud_service_name = '' 
        azure.vm_location = 'West Europe' 
      

     
      azure.ssh_port = '22'

      # Provide the following values if creating a Windows VM
      #azure.winrm_transport = [ 'http', 'https' ] # this will open up winrm ports on both http (5985) and http (5986) ports
      #azure.winrm_https_port = 'A VALID PUBLIC PORT' # customize the winrm https port, instead of 5986
      #azure.winrm_http_port = 'A VALID PUBLIC PORT' # customize the winrm http port, insted of 5985

      #azure.tcp_endpoints = '3389:53389' # opens the Remote Desktop internal port that listens on public port 53389. Without this, you cannot RDP to a Windows VM.
    end

    config.ssh.username = 'vagrant' # the one used to create the VM
    config.ssh.password = 'Lampstack09' # the one used to create the VM
end
